name: CTS Build Action

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository_owner}}/${{github.repository}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: add execute flag to build.sh
      working-directory: ./
      run: chmod +x build.sh


    - name: Build the Docker image
      working-directory: ./
      run: ./build.sh

    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
#    - name: Cache Node.js modules
#      uses: actions/cache@v3
#      with:
#        path: ~/.npm
#        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
#        restore-keys: |
#          ${{ runner.os }}-node-

      ## Pushing to gitHub docker registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CTS_GITHUB_TOKEN }}
    - name: Tag the Docker image
      run: docker tag bean-v2 ghcr.io/linusx1402/bean-v2:latest
      working-directory: ./frontend

    - name: Push the Docker image
      run: docker push ghcr.io/linusx1402/bean-v2:latest
      working-directory: ./frontend